### ISSUE TITLE
Dimensional Doors pocket dimension Bonus heart lose

### ISSUE THREAD

**Issue by KynLeg** [xJon/Hexxit-II#152] opened 2022-05-25 17:31 UTC
Next Problem i noticed if you enter the dimensional doors pocket dimension you lose all you bonus hearts and they dont come back help

**Comment by xJon** [comment] 2022-05-26 14:18
Hi, this is probably a duplicate of https://github.com/xJon/Hexxit-II/issues/151 as it's caused by the same thing. I can keep this open until the next update to see whether the issue gets resolved with the addition of the [Fix Experience Bug](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug/files/3372374) mod.

**Comment by xJon** [comment] 2022-07-26 19:29
Can you test whether this issue is still present with the latest version of the modpack? (`1.4.0`)

**Comment by xJon** [comment] 2022-09-02 18:46
Closed due to inactivity.
Will reopen with the required info!

**Closed by xJon** 2022-09-02 18:46 UTC
Labels: missing info
