### ISSUE TITLE
Ocean Mobs don´t spawn on Multiplayer Server

### ISSUE THREAD

**Issue by GeNeRaLZook** [xJon/Hexxit-II#85] opened 2021-12-20 13:28 UTC
Water Mobs don´t spawn on Multiplayer Servers or they are invisible

I have bought a Multiplayer Server for Hexxit 2 and we can´t find any Squids/Ocean Mobs from Mo´s Creatures. They are maybe spawning but have no Hitbox and be invisible, because some of us were slain by sharks.  When i tried to spawn them with a Spawn Egg they disappear immediately. We also test Hexxit 2 on a Private Server and there is the same issue.

**Comment by xJon** [comment] 2021-12-21 00:02
Thanks for the report, I can confirm the issue and we will look into it!

**Comment by Telunia** [comment] 2021-12-31 16:05
> Thanks for the report, I can confirm the issue and we will look into it!

Is there any update on this issue?

**Comment by xJon** [comment] 2022-01-01 15:51
We know the cause and will fix this in the next update, which should be released pretty soon!

**Comment by xJon** [comment] 2022-01-09 00:13
This is now fixed in version `1.3.0`!

**Closed by xJon** 2022-01-09 00:13 UTC
Labels: fixed
