### ISSUE TITLE
Dimensional Doors update causing issues on server

### ISSUE THREAD

**Issue by jongames** [xJon/Hexxit-II#177] opened 2022-08-13 14:04 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes: Spark, PurpleIRC

Relevant information: Spark thread profiler reports that a bunch of CPU time is being spent on getting entities such as dropped items.  
![image](https://user-images.githubusercontent.com/18472148/184497361-9173902d-c7b9-4051-a055-d4f34c7d1e49.png)

I used timings to show that there are 16287 dropped items in a chunk that was seen once and not even the dimension that I am in when having the bad performance.  
![image](https://user-images.githubusercontent.com/18472148/184497399-38ebfea0-f0a6-40de-ab33-ba5edbe582ca.png)

Therefore I am unsure how there are that many drops when it is essentially untouched land.  This error also occurred when no one was on the server since when I first started the server after updating to 1.4.1 and logged in it was 20 tps and low CPU usage.  I then disconnected & went to sleep, and then wake up to this low tps high cpu state.

Is there any way to debug what caused the numerous dropped items in areas of the map which I was not even in?  And how can I clear these excess drops from these chunks?  I do not see anything when I used dimteleport to tp to the location.  I have used 
https://github.com/Fenixin/Minecraft-Region-Fixer in the past but that was for vanilla minecraft, not forge with custom dimensions.

**Comment by jongames** [comment] 2022-08-13 14:11
Well a restart fixed it and the "dropped items" do not show up on timings report.  But the fact was before I was able to run the server for days without this ever happening and right after the update I have this weird problem occur.  I will update here if it occurs again

**Comment by jongames** [comment] 2022-08-13 14:12
oops, i hit close issue accidentally...

**Comment by jongames** [comment] 2022-08-13 14:12
oops, i hit close issue accidentally

**Comment by xJon** [comment] 2022-08-13 15:55
16287 dropped items in a chunk? That's pretty extreme. The `1.4.0` update was supposed to help CPU usage with the inclusion of [LoliASM](https://www.curseforge.com/minecraft/mc-mods/lolasm). I can't really reproduce your issue easily so it'd be great if you can do further troubleshooting, e.g. what those items were and why weren't they clearing themselves after 5 minutes? I also know there are other server utility plugins and [mods](https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735) that help with that.
Frankly I don't have much experience with server running but I'd gladly try to help in any way I can as I do want the modpack to be friendly for running public servers :)

**Comment by jongames** [comment] 2022-08-16 05:50
![image](https://user-images.githubusercontent.com/18472148/184805609-efa2db03-84ec-4bd1-80e1-288eee725ac4.png)
I did a command to kill dropped items due to the server going to high CPU usage and 10+GB of RAM.  This is a lot of the result: item.item.world_thread which seems to be related to the Dimensional Doors mod https://ftb.fandom.com/wiki/World_Thread .

I am unsure if it happened in previous versions of the dimensional doors mod but I did not notice this occurring before so I believe this is a new problem and I do see you updated the mod with the pack update.  I will take a look into the mod's github issues and report it there too.

**Comment by xJon** [comment] 2022-08-16 18:36
Thank you for the further troubleshooting! Indeed we have updated Dimensional Doors quite a bit recently and these items causing issues in your servers are almost certainly due to that. Thank you for opening the issue directly in the mod repository and I hope that the person who has been working on the latest Dim Doors updates (@TheComputerizer) would be able to help with that.

**Comment by xJon** [comment] 2022-08-17 18:31
@jongames Did you try to turn dropping world thread off in the config and reproduce the issue?

**Comment by jongames** [comment] 2022-08-17 21:48
I did turn it off since I already realized it was an option.  I have not checked on the server since I am pretty busy.  Also it kind of happened randomly before.  Currently, it has not reoccurred but I will check again tomorrow.

**Comment by xJon** [comment] 2022-09-10 18:02
Fixed in `1.4.2` as world thread drops are now disabled by default :)

**Closed by xJon** 2022-09-10 18:02 UTC
Labels: minor bug
