### ISSUE TITLE
Game crash when opening/shortly after opening Traveler's Notebook (Twilight Forest)

### ISSUE THREAD

**Issue by lol-123** [xJon/Hexxit-II#216] opened 2023-11-08 23:47 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/kMhfEPb

**Describe the issue**

Game crash when opening/shortly after opening Traveler's Notebook (Twilight Forest)

**Comment by xJon** [comment] 2023-11-09 01:30
Seems to be a duplicate of https://github.com/xJon/Hexxit-II/issues/212, caused by https://github.com/jbredwards/Fluidlogged-API/issues/186. Thank you for the report!

**Closed by xJon** 2023-11-09 01:30 UTC
Labels: duplicate
