### ISSUE TITLE
Purple Slimesling

### ISSUE THREAD

**Issue by DragonARandom** [xJon/Hexxit-II#54] opened 2021-11-09 02:13 UTC
Unsure if this is a mod pack issue or just a mod issue, but I attempted to use a purple slimesling that I had obtained from one of the underground dungeons and it crashed as soon as I should be slung.

**Comment by xJon** [comment] 2021-11-09 04:29
Hi, can you please attach a crash report?

**Comment by DragonARandom** [comment] 2021-11-09 04:33
Where would i find it?

**Comment by xJon** [comment] 2021-11-09 14:14
`\.technic\modpacks\hexxit-ii\crash-reports\`.

**Comment by DragonARandom** [comment] 2021-11-09 17:02
[crash-2021-11-08_20.04.28-client.txt](https://github.com/xJon/Hexxit-II/files/7506649/crash-2021-11-08_20.04.28-client.txt)

**Comment by DragonARandom** [comment] 2021-11-09 19:15
I did not modify the pack in my way, and when i try to use the purple slimesling again, it lags with about a 50% chance of a crash, I have tried the other three colors and they did not produce any lag outside of terrain generation

**Comment by xJon** [comment] 2021-11-10 14:42
This seems to be a duplicate of https://github.com/SlimeKnights/TinkersConstruct/issues/2470, https://github.com/SlimeKnights/TinkersConstruct/issues/3551. Probably a rare Tinkers bug which is not easy to reproduce, I was not able to myself. There's not much we can do unfortunately but thank you for reporting this nonetheless!

**Comment by xJon** [comment] 2022-01-09 00:41
Closed due to inactivity.
Will reopen if requested.

**Closed by xJon** 2022-01-09 00:41 UTC
Labels: help wanted
