### ISSUE TITLE
Not able launch into Hexxit 2 

### ISSUE THREAD

**Issue by EthanHarper56** [xJon/Hexxit-II#79] opened 2021-12-11 05:38 UTC
when I try to launch Hexxit 2, an error pops up and doesn't let me into Minecraft. the error says that the Chocolate Quest Repoured mod is a possible cause. I already tried redownloading the modpack and it did not fix the issue. what do I do?

**Comment by xJon** [comment] 2021-12-11 15:48
Hi! This would be a duplicate of https://github.com/xJon/Hexxit-II/issues/77. If you're using Mac OS please revert back to version `1.1.0` until Chocolate Quest Repoured releases a fix. Sorry!

**Closed by xJon** 2021-12-11 15:48 UTC
Labels: duplicate
