### ISSUE TITLE
Minecraft failed to start 

### ISSUE THREAD

**Issue by Awonibonga** [xJon/Hexxit-II#93] opened 2022-01-05 21:54 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

A clear description of what the issue is.

An error during startup prevented Minecraft from starting. Chocolate Quest Repoured Mod has been identified as a potential cause.
<img width="766" alt="Screen Shot 2022-01-05 at 21 54 16" src="https://user-images.githubusercontent.com/97198032/148295139-d0feaee6-30d0-4cf3-aa79-db74f4640138.png">

**Comment by xJon** [comment] 2022-01-06 02:34
This is a duplicate of https://github.com/xJon/Hexxit-II/issues/77. For now, play on version `1.1.0`, but a new version with a fix for this will release within the next few days!

**Closed by xJon** 2022-01-06 02:34 UTC
Labels: duplicate

**Comment by Awonibonga** [comment] 2022-01-07 10:58
Thankyou
