### ISSUE TITLE
Hwyla erroring when fighting Walker King boss

### ISSUE THREAD

**Issue by Communism202** [xJon/Hexxit-II#179] opened 2022-08-15 16:19 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: YES
- **Did you add any additional mods**: NO
- **Crash/latest log link (if applicable)**: https://mclo.gs/IFdN5ji

**Describe the issue**

I was running around the world until I found one of those Walker King castle dungeons. Fighting all the normal walkers was fine, but once i got to the king, my game started lagging an insane amount. It seems to only happen when the King hits you with his sword or is just about to hit you, neither his lightning summonings or the creating clones of himself attack does this, but pretty much every time he hits me my game suddenly drops to 0fps and freezes for like 10seconds until he either knocks me far enough away from him or I die because im frozen and cant run away.

I went to the chocolate quest mod devs about this, they tried it themselves with only chocolate quest mod installed and couldnt replicate it, so they told me its probably a mod conflict and i gotta go to you instead, the modpack dev.

i have no idea whats causing it honestly. I doubt its just that the fight is performance intensive, i tried going from 4gb to 8gb, no effect same thing happens. This modpack doesnt really lag all that much for me and seems to run just fine, so i doubt its just my PC being old / weak / bad specs.
Heres my PC specs:
GPU: GeForce GTX 980
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
RAM: 2x 8GB DDR4 RAM Sticks (Corsair)
Resolution: 1920 x 1080, 60Hz
OS: Windows 10

Ive tried a few things, ive tried disabling dynamic lights, ive tried removing my items in my inventory maybe it was some item causing it but nope lol, even if i have nothing in my inventory and just give myself resistance 255 potion effect to survive, it still freezes when he hits me.

**Comment by ACGaming** [comment] 2022-08-15 17:57
`WailaTickHandler_tickClient_ClientTickEvent`
Looks like HWYLA is acting up. Can you remove the mod temporarily and try to replicate the issue without it?

**Comment by Communism202** [comment] 2022-08-15 18:40
> 

Hello ACGaming,

Thank you! Yes, that was indeed the issue. Out of all things i expected to be the conflict, i didnt expect HWYLA / WAILA to be the reason. I removed it from the modpack, and suddenly, it works perfectly. The walker king is hitting me around his castle with his sword just fine now without any freezes or fps drops.

Well, problem is, HWYLA is kinda important, and living without it is certainly a hassle xd

**Comment by ACGaming** [comment] 2022-08-15 19:37
[The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe) might be an alternative for you.

**Comment by Communism202** [comment] 2022-08-15 20:17
I guess @xJon could try to substitute HWYLA in the modpack with one probe, if one probe doesnt shit itself while fighting the Walker King like HWYLA does.

**Comment by xJon** [comment] 2022-08-15 23:25
That's unfortunate! I tried to reproduce this myself unsuccessfully, but I understand this is an issue to some players.
I'd rather not replace Hwyla for One Probe at this point, but perhaps we could find a workaround. Did you by any chance enable Waila to show entities?

**Comment by Communism202** [comment] 2022-08-16 11:58
> That's unfortunate! I tried to reproduce this myself unsuccessfully, but I understand this is an issue to some players. I'd rather not replace Hwyla for One Probe at this point, but perhaps we could find a workaround. Did you by any chance enable Waila to show entities?
![Unbenannt](https://user-images.githubusercontent.com/67879039/184874042-cccb4ca7-c520-4045-a427-04b97bb178c1.png)
still happens with these settings ):

**Comment by ACGaming** [comment] 2022-08-16 14:35
`See WailaErrorOutput.txt for more information`
Can you share this file as well? Should be somewhere in the modpack directory.

**Comment by ACGaming** [comment] 2022-08-16 14:42
Just noticed this in the log: `Caught unhandled exception : [class info.tehnut.soulshardsrespawn.compat.hwyla.DataProviderCageBorn] net.minecraft.util.ReportedException: Saving entity NBT` which normaly only applies to mobs spawned by Soul Shards‘ mob spawners (soul cages). Very odd.

**Comment by Communism202** [comment] 2022-08-16 17:15
> `See WailaErrorOutput.txt for more information` Can you share this file as well? Should be somewhere in the modpack directory.
[WailaErrorOutput.txt](https://github.com/xJon/Hexxit-II/files/9353028/WailaErrorOutput.txt)
heres the file

**Comment by Communism202** [comment] 2022-08-16 17:16
> Just noticed this in the log: `Caught unhandled exception : [class info.tehnut.soulshardsrespawn.compat.hwyla.DataProviderCageBorn] net.minecraft.util.ReportedException: Saving entity NBT` which should only occur with mobs spawned by Soul Shards‘ mob spawners (soul cages). Very odd.

huh thats weird, i havent even touched that mod at all.

**Comment by ACGaming** [comment] 2022-08-16 17:32
`info.tehnut.soulshardsrespawn.compat.hwyla.DataProviderCageBorn.getWailaBody`
This confirms it, seems to be a rare cross-compatibility issue whilst accessing NBT data from entities. Can you test again without Soul Shards loaded for clarity?

**Comment by Communism202** [comment] 2022-08-16 21:34
> `info.tehnut.soulshardsrespawn.compat.hwyla.DataProviderCageBorn.getWailaBody` This confirms it, seems to be a rare cross-compatibility issue whilst accessing NBT data from entities. Can you test again without Soul Shards loaded for clarity?

aight lets see, hwyla back in, soulshardsrespawn out, aaandd....

yup, no freezes or performance drops whatsoever while the king is punching me

so i guess its either removing soulshards or hwyla? guess ill just remove soulshards lol pretty sure thats just a spawner mod from what ive seen of it, never was gonna use it anyway

**Comment by xJon** [comment] 2022-09-10 18:02
Should be fixed in `1.4.2` thanks to @ACGaming :)

**Closed by xJon** 2022-09-10 18:02 UTC
Labels: minor bug
