### ISSUE TITLE
Something went wrong while trying to teleport you

### ISSUE THREAD

**Issue by RanzV7** [xJon/Hexxit-II#109] opened 2022-01-18 18:05 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: link to log / not applicable

**Describe the issue**

 Everytime I go through this portal this pops up in the chat: Something went wrong while trying to teleport you.
 Its the 1x2 portal which gets created by the game on the overworld.

**Comment by xJon** [comment] 2022-01-18 18:32
Hi! Can you please include a game log from the session this error occurred? You can find it in the modpack's installation folder, under the `logs` folder.

**Comment by xJon** [comment] 2022-01-18 21:40
Closing this as it is most likely a duplicate of https://github.com/xJon/Hexxit-II/issues/97.

**Closed by xJon** 2022-01-18 21:40 UTC
Labels: duplicate
