### ISSUE TITLE
Fairy Lights on fences don't work in 1.2.0

### ISSUE THREAD

**Issue by DragaoNimhe** [xJon/Hexxit-II#78] opened 2021-12-10 02:37 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no; but plugins are present (yet i believe unrelated)
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Fairy lights and pennants (all items associated with fairy mod) are not visible in 1.2.0. Their hitbox can still be seen.

**Comment by xJon** [comment] 2021-12-10 04:14
This was supposed to be fixed in `1.2.0` and indeed I cannot reproduce this issue:
![image](https://user-images.githubusercontent.com/8945347/145516287-581ad58b-415d-46ec-af12-063c24effb57.png)

**Comment by DragaoNimhe** [comment] 2021-12-10 05:00
That is SO strange. They were functional for us pre-1.2.0 but 1.2.0 is what broke them lol! I'll do more testing and get back to you with further information about what/where the conflict may be. Thank you for your EXTREMELY quick reply!

**Comment by xJon** [comment] 2021-12-10 05:07
Pre-1.2.0 there was an incompatibility between Entity Culling and Fairy Lights which caused the issue, but in 1.2.0 we updated Entity Culling to fix this!

**Comment by DragaoNimhe** [comment] 2021-12-10 05:34
Thank you so much for that info!

**Comment by DragaoNimhe** [comment] 2021-12-10 05:37
Interesting. I thought for sure it would be an issue with my server, but even in singleplayer (I'm simply on the default update with no modifications) the issue persists. I'm not even using so much as optifine.
![image](https://user-images.githubusercontent.com/12823393/145522835-177de586-237e-4320-95fa-aefd4d5bb4ad.png)

**Comment by DragaoNimhe** [comment] 2021-12-10 05:38
I can attempt a full re-install of the pack and see if that fixes the issue, if you'd like me to?

**Comment by xJon** [comment] 2021-12-10 05:56
Yes that'd be a good idea :)

**Comment by DragaoNimhe** [comment] 2021-12-10 06:05
Sadly after a full re-install the issue persists.

**Comment by DragaoNimhe** [comment] 2021-12-10 06:14
Update: Had my girlfriend download a fresh version on her pc and she has the same issue. For the record, several of my admins have the issue, as well.

**Comment by xJon** [comment] 2021-12-11 18:35
That's really odd. It's double odd that you had no issues before `1.2.0`.
Can you please post exact steps to reproduce the issue?

**Comment by DragaoNimhe** [comment] 2021-12-11 21:45
I don't believe I'm doing anything terribly strange, but here's what I've done during testing.
1. Go to modpack options and delete pack.
2. Re-install fresh pack.
3. Create a single-player world on creative mode.
4. Place 2 fences in a straight line between 2-3 blocks apart.
5. Connect the fences with a strand of fairy lights.
These are the steps my girlfriend and I both took to produce the screenshot pictured above, on two seperate (and quite nice/up to date <3) pc's.
My admins have done pretty much the same, but instead of logging into singleplayer worlds, have logged into our server; where we had functional fairy lights all around spawn on the 1.1.0 update. I'll include some images of those working.
Here, I dm'd a friend MINUTES before the 1.2.0 update dropped excited that we were about to launch (oh that timing haha).
![image](https://user-images.githubusercontent.com/12823393/145692567-bc59f270-9304-438e-8fa7-0d20e0ff0aa1.png)
And here, you can see pennants and lantern-type fairy lights throughout the spawn; again this was on 1.1.0.
![image](https://user-images.githubusercontent.com/12823393/145692595-f89e73a9-a56c-471f-b02e-13e119f65d5a.png)

**Comment by xJon** [comment] 2021-12-11 22:10
First of all that's an amazing build!
I've done some testing and it seems the issue is to do with the fences & Entity Culling again. I will forward this bug report to the mod author of Entity Culling. Thank you!

**Comment by DragaoNimhe** [comment] 2021-12-11 23:18
Extremely happy to be a help! We weren't even aware that they could be hung -not- on fences, haha!

Sidenote: Is there a way I would be able to contact you on discord with a brief and unrelated topic? (Not a bug report). I looked to see if there was a hexxit discord and couldn't find one, perhaps I'm google-dumb from working too much on server launches haha!

**Comment by xJon** [comment] 2021-12-11 23:21
There's a Hexxit II channel on Technic's Discord :)
https://discord.com/invite/technic

**Comment by DragaoNimhe** [comment] 2021-12-11 23:22
Of course! Technic! I feel silly for not looking there. Thank you again for all the help!

**Comment by xJon** [comment] 2022-01-09 00:14
This is now fixed in version `1.3.0`!

**Closed by xJon** 2022-01-09 00:14 UTC
Labels: fixed
