### ISSUE TITLE
Server error(crash report) but without affecting the performance

### ISSUE THREAD

**Issue by TomasGnG** [xJon/Hexxit-II#34] opened 2021-10-31 10:30 UTC
The error:
https://www.toptal.com/developers/hastebin/fezoluyojo.rb

**Comment by xJon** [comment] 2021-10-31 13:49
Can you attach a full game log? It will be useful for the developer's debugging. Thank you!

**Comment by TomasGnG** [comment] 2021-10-31 16:01
Here is the file its kinda big(19mb)
[Download](https://workupload.com/file/cEkaRcetTZ9)

**Comment by xJon** [comment] 2021-10-31 17:18
Thank you, I've forwarded it to the mod author. For now I will close this as it's a duplicate of https://github.com/xJon/Hexxit-II/issues/12 but your report is very helpful!

**Closed by xJon** 2021-10-31 17:18 UTC
Labels: duplicate
