### ISSUE TITLE
Teleporting issue

### ISSUE THREAD

**Issue by Dubboyphat** [xJon/Hexxit-II#100] opened 2022-01-14 18:09 UTC
I found a Limbo portal and decided to go in and work through it. But when I went in, there was a notification that there was a problem teleporting me. screen stayed black so I had to reload. When I did, it through me into the void and I lost all my inventory. How can I get it back, if at all?

**Comment by xJon** [comment] 2022-01-18 19:17
Thank you for the report! In this case, I'd recommend rolling back to a world backup.
Closing this issue as it is a duplicate of https://github.com/xJon/Hexxit-II/issues/97.

**Closed by xJon** 2022-01-18 19:17 UTC
Labels: duplicate
