### ISSUE TITLE
Mushroom Island Crashes when disabling Eyes in the Darkness spawns

### ISSUE THREAD

**Issue by Created-Creation** [xJon/Hexxit-II#237] opened 2024-05-15 02:31 UTC
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

Link always fails upon clicking the Get Link button.

### If you have any, please provide a list of additional mods

No additional mods installed.

### Please describe the issue you are experiencing

Whenever I get within rendering distance of a Mushroom Island biome, the game crashes, and whenever I try to rejoin it crashes immediately. I cannot get within rendering distance at all. The mod cited to cause the crash is "Unknown" and clicking the Get Link button always just fails. Most recent crash file is titled "crash-2024-05-14_19.29.33-client.txt" though this issue has been going on for at least a couple weeks. I literally cannot find any other information about this.

In case of relevancy:
- I configured the Eyes in the Darkness mod so that EnableNaturalSpawn, EyesAttackWhileLit, and Jumpscare are all set to false (out of my irritation towards jumpscares and also the Eyes mobs in general)
- I have 64-bit Java installed, version 8, update 401, build 1.8.0_401-b10
- I have tried leaving and rejoining worlds, restarting technic, and restarting my computer, none of which fixed the problem
- In addition to with different settings on survival, going into a creative world, finding a mushroom island with nature's compass, and teleporting to it in an otherwise normal world also trigger the crash

**Comment by xJon** [comment] 2024-05-15 15:45
Can you find your crash report over `\modpacks\hexxit-ii\crash-reports\` and copy it over to https://mclo.gs?

**Comment by Created-Creation** [comment] 2024-05-15 23:58
Just did.

**Comment by Created-Creation** [comment] 2024-05-15 23:59
(closed on accident, issue remains)

**Comment by xJon** [comment] 2024-05-16 00:38
Can you copy the link?

**Comment by Created-Creation** [comment] 2024-05-16 00:51
Right, my b

https://mclo.gs/wCUQZ4K

**Comment by Created-Creation** [comment] 2024-05-16 00:51
(accidental close again - new to github)

**Comment by xJon** [comment] 2024-05-16 01:16
A bit of a shot in the dark, but can you try to disable `Entity Tracker` (change value of from `true` to `false`) in `\modpacks\hexxit-ii\config\UniversalTweaks.cfg`?

To find the modpack's installation folder:
> 1. Select the `MODPACKS` tab, then click on `Hexxit II`
> 2. Click on `Modpack Options` ⚙ in the top right corner
> 3. Click on `Open` at the top right corner of the pop-up window

**Comment by Created-Creation** [comment] 2024-05-16 02:58
Looks like the same things happened again

**Comment by xJon** [comment] 2024-05-16 05:38
I am unable to reproduce this issue myself in a creative testing world. Can you reproduce this issue in a new world? (You can utilise Nature's Compass to locate & teleport to the biome)

**Comment by xJon** [comment] 2024-05-16 06:06
Thanks to a comment from @ACGaming, I can confirm that disabling `EnableNaturalSpawn` is the cause for this issue. I will experiment with workarounds

**Comment by xJon** [comment] 2024-05-16 06:29
@Created-Creation Can you try to keep the default `eyesinthedarkness.cfg` configs, and instead edit `\modpacks\hexxit-ii\config\incontrol\spawn.json` to have this block at the end? (notice the added comma on the previous block)
```
,	{
		"mod": "eyesinthedarkness",
		"result": "deny"
	}
```
Let me know how it goes.

**Comment by ACGaming** [comment] 2024-05-16 06:53
Might just be easier to remove the mod in this case.

**Comment by xJon** [comment] 2024-05-16 06:56
Oh, right. That's true.

**Comment by Created-Creation** [comment] 2024-05-16 13:21
Alright, I can handle dealing with Eyes until a fix is found, thanks for all the help!

**Comment by Created-Creation** [comment] 2024-05-16 13:26
Tried adding it to spawn.json and hexxit won't start from the launcher. I tired disabling the mod as well but it didn't work, and I'm worried about how it will affect playing multiplayer with others.

**Comment by xJon** [comment] 2024-05-16 16:46
> Tried adding it to spawn.json and hexxit won't start from the launcher

Did you add a comma after the previous block? Can you share a screenshot of how the config file looked like?

**Comment by Created-Creation** [comment] 2024-05-16 21:04
That might be a bit tricky, but yeah, I looked at how all the other blocks were formatted and did the exact same thing, triple-checked it and all.

**Comment by Created-Creation** [comment] 2024-05-16 21:43
I don't remember the exact time so it'll take a bit.

**Comment by Created-Creation** [comment] 2024-05-16 21:45
I'm going to reattempt it and get the log from there. Will doing this affect multiplayer?

**Comment by Created-Creation** [comment] 2024-05-16 21:53
I found that I hadn't hit the default button like I thought I had, and it's running as normal with the code block at the end.

**Comment by Created-Creation** [comment] 2024-05-16 21:59
Turns out I hadn't hit the set to default but instead a different button, my b, was tired. It's working properly now with the code block in, though the tab indent was deleted because the other code blocks didn't have those. Idk if it's the tab removal or the setting to default, but one or both seems to have done the trick. Thanks so much for all the help!

**Comment by xJon** [comment] 2024-05-16 22:03
Glad we figured out a workaround! Indents shouldn't affect the config, only brackets and commas. And as it's a config file rather than a mod change, it usually won't affect multiplayer. 
Closing this as `wontfix`.

**Closed by xJon** 2024-05-16 22:03 UTC
Labels: minor bug, mod issue
