### ISSUE TITLE
Battletower Golem Model is stuck/glitched

### ISSUE THREAD

**Issue by git-h1gh** [xJon/Hexxit-II#46] opened 2021-11-06 22:11 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (Optifine)
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

The Model of the Battletower Golem get's stuck if he wakes up, he is still moving/attacking but you can't see his real position. This Issue is occuring only on Servers (default configs)
Video showing the Bug: https://streamable.com/ntvwkv

**Comment by xJon** [comment] 2021-11-06 23:02
Did you try relogging? Unfortunately the mod is not in active development so there's not much we can do about this.

**Comment by git-h1gh** [comment] 2021-11-07 02:40
Relogging will just update the postion too the place where the Golem actually is, but the issue itself is not fixed.

The Issue is only occuring since the 1.1.0 Version.

**Comment by xJon** [comment] 2021-11-10 14:31
I doubt this issue has something to do with the modpack update since Infernal Mobs did not change. Can you reproduce this with other towers or is it just with one golem? Do you have any steps in order to reproduce the issue?

**Comment by git-h1gh** [comment] 2021-11-11 02:25
This happens with every Golem, mz friend has the same issue and it only happens on the server - singleplayer works fine

**Comment by Ve6om** [comment] 2021-11-12 14:35
Getting same issue on server.

**Comment by xxeonUK** [comment] 2021-11-20 11:55
Hi i am getting the exact same issue however mine is on every tower and he gets stuck at the top. 

Please see this video - https://youtu.be/sUYGxdj68Do

I made another bug report not realising. This only happens on the server not single player.

**Comment by xJon** [comment] 2021-11-21 02:02
Do you have any steps to reproduce this issue or does it happen at random?
For now I've forwarded the issue to the mod author.

**Comment by Ve6om** [comment] 2021-11-21 02:03
> Do you have any steps to reproduce this issue or does it happen at random? For now I've forwarded the issue to the mod author.

It happens to every single golem. I don't believe this a battletowers issue as it doesn't happen standalone.

**Comment by xxeonUK** [comment] 2021-11-21 13:30
It happens to me on every battletower golem as well. Just to clarify this is definitely a server sided issue.

**Comment by xJon** [comment] 2021-11-29 15:03
@git-h1gh @Ve6om @xxeonUK Do you have any steps in order to reproduce this issue on a server? It doesn't happen to everyone and it didn't for us on multiplayer testing. Does it occur even if you explore different towers, or start a new world?
Also, did you modify the modpack or server in any way, installed any plugins?
Thanks in advance!

**Comment by xxeonUK** [comment] 2021-11-30 00:27
Hi i tried it on a new world today with a friend and the exact same thing happened. This was on a fresh server.

Please see youtube vid - https://youtu.be/hNWotdyisrg

You may have to wait for it to proccess for full quality :)

**Comment by xJon** [comment] 2021-11-30 15:50
How are you running your server? Is it a LAN server?

**Comment by xxeonUK** [comment] 2021-11-30 16:46
I have tried it on a server ran on a personal pc by me. I have also tried it on a server hosted by https://zap-hosting.com/

It happens on both. It is not a LAN server

**Comment by Ve6om** [comment] 2021-12-04 18:08
> @git-h1gh @Ve6om @xxeonUK Do you have any steps in order to reproduce this issue on a server? It doesn't happen to everyone and it didn't for us on multiplayer testing. Does it occur even if you explore different towers, or start a new world? Also, did you modify the modpack or server in any way, installed any plugins? Thanks in advance!

It happens on every tower and even if you just /summon the golem. Tested on a fresh server instance as-well.

**Comment by xJon** [comment] 2021-12-05 03:19
@git-h1gh @Ve6om @xxeonUK Did this happen on all versions of the modpack?

**Comment by Ve6om** [comment] 2021-12-05 03:24
> @git-h1gh @Ve6om @xxeonUK Did this happen on all versions of the modpack?

I never personally tested older versions, @git-h1gh mention this: 
![image](https://user-images.githubusercontent.com/42916774/144732187-80d9a92d-e548-438c-ae83-5023981866e3.png)

**Comment by xJon** [comment] 2021-12-05 04:15
@Ve6om Thank you for pointing this out! I'll be doing some testing & changes to try to fix this in the upcoming modpack update.

**Comment by Ve6om** [comment] 2021-12-05 04:22
> @Ve6om Thank you for pointing this out! I'll be doing some testing & changes to try to fix this in the upcoming modpack update.

No problem! Let me know what you find! 😄

**Comment by xJon** [comment] 2021-12-05 18:29
I've identified the issue & will try to fix it with the mod author :)

**Comment by Ve6om** [comment] 2021-12-05 20:25
> 

What mod was causing it?

**Comment by xxeonUK** [comment] 2021-12-05 20:28
> I've identified the issue & will try to fix it with the mod author :)

Great to hear, will you let us know if any changes are made?

**Comment by xJon** [comment] 2021-12-06 00:00
@Ve6om @xxeonUK After many hours of testing I can confirm this is an incompatibility caused by the combination of Hexxit World, Battle Towers, Just Enough Resources & Mo' Creatures. Really unpredictable. We will look into fixing this from Hexxit World's end

**Comment by xJon** [comment] 2021-12-08 00:45
This is fixed in `1.2.0` :)

**Closed by xJon** 2021-12-08 00:45 UTC
Labels: fixed
