### ISSUE TITLE
Teleporting between Nether and Overworld

### ISSUE THREAD

**Issue by Polda03** [xJon/Hexxit-II#103] opened 2022-01-16 12:59 UTC
**Basic details**
Im using java 64
I haven't added any mods
Crashing always when i teleport back to overworld
https://paste.ubuntu.com or https://pastebin.com/index.

![image](https://user-images.githubusercontent.com/97835277/149660900-1c7dd419-2050-4400-92f7-caff200aea5a.png)

**Comment by xJon** [comment] 2022-01-17 00:28
Can you please include the crash log?

**Comment by xJon** [comment] 2022-01-18 21:39
Closing this as it is most likely a duplicate of https://github.com/xJon/Hexxit-II/issues/97.

**Closed by xJon** 2022-01-18 21:39 UTC
Labels: duplicate
