### ISSUE TITLE
Fairy Light's Do Not Show a Texture

### ISSUE THREAD

**Issue by Packratter** [xJon/Hexxit-II#71] opened 2021-11-21 23:20 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**:  **yes**
- **Did you add any additional mods**:  **no**
- **Crash/latest log link (if applicable)**: **not applicable**

A clear description of what the issue is:

When you place the lights from the fairy light mod. You see the hit box of the string of lights, however there is no texture. In addition, there is light output from the lights, but still no actual texture.

**Comment by xJon** [comment] 2021-11-22 14:29
This is a duplicate of https://github.com/xJon/Hexxit-II/issues/11, but thankfully this has been fixed with the latest Entity Culling update, so you can expect the fix to make it to the modpack soon :)

**Closed by xJon** 2021-11-22 14:29 UTC
Labels: duplicate
