### ISSUE TITLE
Endportal stuck

### ISSUE THREAD

**Issue by W4iv3lt** [xJon/Hexxit-II#102] opened 2022-01-16 10:53 UTC
**Basic details**
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://pastebin.com/axv1xuyX

**Describe the issue**
I was jumping from the end into the normal world and after skipping the outro, the internal server were shut down. Now when I am trying to join the world the game freezes again and the server shut down.
The game says that Chocolate Quest Repoured Mod might be the problemmaker

**Comment by W4iv3lt** [comment] 2022-01-18 07:57
Hello again,
for your information, after I deleted my inventory data in the data directory and the backpack directory, I could join the world again:
Maybe there was/is a bug.

**Comment by xJon** [comment] 2022-01-18 19:23
Thank you for the report! This will be worked on. Keep in mind you could also revert to world backups.
Closing as it is a duplicate of https://github.com/xJon/Hexxit-II/issues/97.

**Closed by xJon** 2022-01-18 19:23 UTC
Labels: duplicate
